### ISSUE TITLE
一个神奇的问题，net.pth.corrupted

### ISSUE THREAD

**Issue by jiafw** [smthemex/ComfyUI_Hallo2#13]
模型已经正常下载好了，每次加载的时候，hallo文件夹的net.pth模型总是会变成net.pth.corrupted这个，加了.corrupted后缀。

模型是直接从huggingface下的，重试下载好多次了，都会出现这个错误。

因为后缀变了所以读不到

**Comment by smthemex** [comment]
我看了下代码，按理应该不会出错。只有识别到没有模型才会自动下载。
你运行的时候，看一些在控制台是否有“no net.pth in {你的路径} ,try download from huggingface! ”打印出来，如果没有文件才会判定没有模型，开启自动下载。
你可以试试删掉hallo2整个文件夹，新建一个，然后复制模型进去。

**Comment by jiafw** [comment]
来反馈下，解决了，原因就是环境问题，最后还是换了个环境，按requirements安装了一遍，但不确定是哪个包，没有一一对比。

没安装前，报错大概是这样的，在已经注释掉下载的情况下，也验证了存在这个文件的情况下，还是会出现corrupted：

![屏幕截图 2024-10-31 105130](https://github.com/user-attachments/assets/bc48a7fd-7d20-42ac-926c-9cc55d135bd0)

看起来可能fooocus存在冲突，我删除fooocus插件后也不行，所以我直接换了个环境重装了，稍微处理下环境错误，马上就过了。

后面还遇到音频存在但是找不到的问题，就是ffmpeg没有，装了下就好了。
