### ISSUE TITLE
求助：多次测试，问题一样。每次读到net.pth这个模型 comfyui 就关

### ISSUE THREAD

**Issue by tiandaoyuxi** [smthemex/ComfyUI_Hallo2#9]
多次测试，问题一样。每次读到net.pth comfyui 就关
got prompt
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
[] ['conv_out.bias', 'conv_out.weight']
loaded temporal unet's pretrained weights from D:\Comfy_UI\ComfyUI\models\checkpoints\SD1.5\diffusion_pytorch_model.safetensors ...
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from D:\Comfy_UI\ComfyUI\models\Hallo\motion_module\mm_sd_v15_v2.ckpt
Loaded 453.20928M-parameter motion module
loaded weight from : D:\Comfy_UI\ComfyUI\models\Hallo\hallo2\net.pth .

d:\Comfy_UI>pause
请按任意键继续. . .

 D:\Comfy_UI\ComfyUI\models\hallo\hallo2 的目录

2024/10/21  11:46    <DIR>          .
2024/10/21  11:46    <DIR>          ..
2024/10/21  15:52     4,850,767,602 net.pth
2024/10/21  11:01       904,732,980 net_g.pth
               2 个文件  5,755,500,582 字节
               2 个目录 1,866,146,275,328 可用字节

**Comment by smthemex** [comment]
还是2.4.1的torch问题，你试过升级safetensors 库没有，因为我测试2.4.0跑是没问题的

**Comment by tiandaoyuxi** [comment]
还是2.4.1的torch问题，你试过升级safetensors 库没有，因为我测试2.4.0跑是没问题的  

safetensors 库没有请问这个是什么库？ 这个不是模型的后缀吗，我不是很理解这个需要如何

**Comment by tiandaoyuxi** [comment]
> safetensors 库

请问有版本建议吗我去升级试试

**Comment by smthemex** [comment]
这是diffuser自带的，我看你的版本都是最新的，看来我是遗漏了net的加载方式，我改一下，稍等

**Comment by tiandaoyuxi** [comment]
> 这是diffuser自带的，我看你的版本都是最新的，看来我是遗漏了net的加载方式，我改一下，稍等

safetensors                             0.4.4

**Comment by smthemex** [comment]
你更新后再测试一下

**Comment by tiandaoyuxi** [comment]
> > 这是diffuser自带的，我看你的版本都是最新的，看来我是遗漏了net的加载方式，我改一下，稍等
> 
> safetensors 0.4

> 你更新后再测试一下

got prompt
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
[] ['conv_out.bias', 'conv_out.weight']
loaded temporal unet's pretrained weights from D:\Comfy_UI\ComfyUI\models\checkpoints\SD1.5\diffusion_pytorch_model.safetensors ...
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from D:\Comfy_UI\ComfyUI\models\Hallo\motion_module\mm_sd_v15_v2.ckpt
Loaded 453.20928M-parameter motion module
loaded weight from : D:\Comfy_UI\ComfyUI\models\Hallo\hallo2\net.pth .

d:\Comfy_UI>pause
请按任意键继续. . . 问题依旧 可以的话也可以加我微信或者qq我可以开远程给大佬检查下  有必要我也可以升级safetensors 到0.4.5

**Comment by tiandaoyuxi** [comment]
![image](https://github.com/user-attachments/assets/5ff973f6-e4b0-49e8-943f-7733206f8f66)
![image](https://github.com/user-attachments/assets/8402e40e-4487-4d25-880a-52456a18a109)

**Comment by smthemex** [comment]
呃，感觉不是这里的问题， 你是跑哪个节点报错?

**Comment by tiandaoyuxi** [comment]
> 呃，感觉不是这里的问题， 你是跑哪个节点报错?

“hallopreimgandauido” 如上图

**Comment by smthemex** [comment]
你把Q号发我邮箱muweiji@live.com，我远程看一下吧

**Comment by tiandaoyuxi** [comment]
好的，我翻墙下完两个模型就发。
主要关梯子防止远程卡慢 。请问用什么软件 todesk、anydesk 还是RustDesk？

**Comment by smthemex** [comment]
这些模型走国内的hf镜像就好，除非是最新的，也不用梯子吧，还有魔搭平台呢
________________________________
发件人: tiandaoyuxi ***@***.***>
发送时间: 2024年10月22日 2:52
收件人: smthemex/ComfyUI_Hallo2 ***@***.***>
抄送: smthemex ***@***.***>; Comment ***@***.***>
主题: Re: [smthemex/ComfyUI_Hallo2] 求助：多次测试，问题一样。每次读到net.pth这个模型 comfyui 就关 (Issue #9)


好的，我翻墙下完两个模型就发。
主要关梯子防止远程卡慢 。请问用什么软件 todesk、anydesk 还是RustDesk？

―

**Comment by tiandaoyuxi** [comment]
> 你把Q号发我邮箱[muweiji@live.com](mailto:muweiji@live.com)，我远程看一下吧

已发请查收邮件
